### ISSUE TITLE
 On Authorization

### ISSUE THREAD

**Issue by zhuangfengzi** [PetoiCamp/OpenCat-Old#13]
Is this project authorized?

If we use this open source code for simple development, such as Bluetooth version or other, to make a basic mechanical cat, can we manufacture and sell it?

**Comment by Aiki-bot51** [comment]
I dont think so.... And you shouldnt rhongzhong li has worked hard gor this code. Maybe try distributing his nybble

**Comment by zhuangfengzi** [comment]
@Aiki-bot51 ，
I read the topic “License and STL files?”, did not understand!
That's why I asked this question.

**Comment by Aiki-bot51** [comment]
For instance there is a copyright on the nybble.ino code @zhuangfengzi
If you can do 3d modeling please contact me on aikyodzaki@gmail.com

**Comment by zhuangfengzi** [comment]
@Aiki-bot51
What can I say here in the future?

The happiest thing is that Professor Li will share it all now!

My main purpose of studying is to improve my life. I can hardly eat any food now. If you can't earn money, what else can you do?

What you learn must always be translated into value! The most vulgar way to say it is money!

**Comment by borntoleave** [comment]
Hi, 
Sorry for late response. I'm fried working on sending out orders. Will return to you with my vision on this project.
