### ISSUE TITLE
Sugestion and a propose to help setup the petoi.com or it's documentation as GitHub Page

### ISSUE THREAD

**Issue by fititnt** [PetoiCamp/OpenCat-Old#2]
To start, I'm a fan of this project, even if I'm not a hardware developer, for what you want to accomplish. In short term I cannot help with code or specific things related to the opencat itself, I guess that the most non-generic help [that I'm doing witch at some point could be more pertinent with this project is a working group about ChatOps](https://github.com/fititnt/chatops-wg/issues). Anyway, as start, there are few 'undesired, but necessary jobs' that helps promote something that could be easier to me or colleagues to start and explain how to maintain. This is one of they.

----

The <https://www.petoi.com/> now is hosted on Wix. One alternative is use GitHub Pages <https://pages.github.com/> to host the pages, stick with the static generator Jekyll which helps with some repetitive tasks and have some themes <http://jekyllthemes.org/>, then configure a custon domain with CNAME file and still able to use SSL for free without need to pay for hosting, put the website on a free cloudflare account.

Even if the main website still on Wix (I can understand that is faster in sort term) this could still be done later with information related to documentation or for what the [Wiki on this repository](https://github.com/PetoiCamp/OpenCat/wiki) is used. 

If have interest, I could personally help with the start here. The first steps could take a lot of time to understand the basics, but after is configured, is relative simple to maintain, and I could document how to do it. Is not far from just add markdown files in a directory and still allows contributions from people outside the project via pull requests.

## Some some examples

- https://github.com/pokemongovet/pokemongovet.github.io & https://pokemongovet.github.io/
- https://github.com/webiwg/acessibilidade-web-pt & http://acessibilidade.pt.webiwg.org/

**Comment by borntoleave** [comment]
Hi, 
Thanks for reminding me of this alternative. I remember seeing this option when building my personal website two years ago. The two example sites look very nice. I assume that its GitHub gene makes it easier to update codes' documentation? If so, I want to use it for a polished documentation for the project. 

I have very few front-end experience and hope to focus my early resources on the hardware. For the Wix site, it's a WYSIWYG host for general public and later commercial use. It has a convenient online store feature and I starved to buy that .com domain. 

Solution: I'd love to add one tab as Documentation/Support on Wix page that links to the Jekyll pages. 

Before finding proper funding and launching our products, I'm hosting a small group (my students and some enthusiasts) in my private repository. Would you like to join and contribute to the discussion?

**Comment by fititnt** [comment]
cc @cdiegosr

**Comment by fititnt** [comment]
I talked to Diego. You can add @cdiegosr and me at the private repository. Diego is a old friend with a history to help non-profit groups with internet. He even said me a hour ago that already traveled to China for one month to visit hackerspaces & makerspaces.

**Comment by cdiegosr** [comment]
Hi guys! If i can help, let´s do it!

**Comment by fititnt** [comment]
Just and update: at https://github.com/fititnt/chatops-wg/issues/31 @cdiegosr and I are seeing how to collaborate with projects like yours and document the process so that we can apply in other similar projects.

This can take some time because, for obvious reasons, any suggestion should be better than what already is used (in this case the Github wiki and the Wix page) not only the final result, but the easy to use and maintain you as a maintainer of the project.
